### ISSUE TITLE
hellworld deployment fails

### ISSUE THREAD

**Issue by mboersma** [kelseyhightower/kubernetes-initializer-tutorial#10]
The docker image referenced in [Create the helloworld deployment](https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/master/docs/initializing-deployments.md#create-the-helloworld-deployment) doesn't exist, so the deployment fails:

```console
$ docker pull hightowerlabs/helloworld:0.0.1
Error response from daemon: manifest for gcr.io/hightowerlabs/helloworld:0.0.1 not found
```

Didn't see "hightowerlabs" at https://console.cloud.google.com/gcr/images/google-containers/GLOBAL either, so I assume the image isn't published there.

**Comment by armyofevilrobots** [comment]
I got past this with:
`image: gcr.io/hightowerlabs/helloworld:1.0.0`
